version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    networks:
        - ostock
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    networks:
      - ostock
  licensingservice:
    image: ostock/license-service:0.0.2-SNAPSHOT
    environment:
      PROFILE: "dev"
    depends_on:
      - database
      - configserver
    ports:
      - "8080:8080"
    links:
      - configserver
    networks:
      - ostock

networks:
  ostock:
    driver: bridge
