spring:
    application:
      name: organization-service
    profiles:
      active: dev
    config:
      import: optional:configserver:http://configserver:8071
    cloud:
        config: 
            uri: http://configserver:8071
            failFast: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG