spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://configserver:8071
  cloud:
    config:
      uri: http://configserver:8071

    loadbalancer:
      ribbon:
        enabled: false